config/packages: replace nixd with nil because niche errors
While using nil I was encountered with following error repeatedly:

Notification title: Request textDocument/documentSymbol failed
Log:
[Error - 4:37:17 PM] Request textDocument/documentSymbol failed.
Error: name must not be falsy
        at vf.validate (file:///nix/store/k6h7ajf6sy6g007dq4hlq0kxsgjynnq4-vscode-1.102.3/lib/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:22554)
        at new vf (file:///nix/store/k6h7ajf6sy6g007dq4hlq0kxsgjynnq4-vscode-1.102.3/lib/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:22843)
        at sZ (/home/ali/.vscode/extensions/jnoortheen.nix-ide-0.4.22/dist/extension.js:35:72651)
        at sZ (/home/ali/.vscode/extensions/jnoortheen.nix-ide-0.4.22/dist/extension.js:35:72828)
        at G (/home/ali/.vscode/extensions/jnoortheen.nix-ide-0.4.22/dist/extension.js:35:46482)
        at Object.fV [as map] (/home/ali/.vscode/extensions/jnoortheen.nix-ide-0.4.22/dist/extension.js:35:46568)
        at Object.n9 [as asDocumentSymbols] (/home/ali/.vscode/extensions/jnoortheen.nix-ide-0.4.22/dist/extension.js:35:72618)
        at B (/home/ali/.vscode/extensions/jnoortheen.nix-ide-0.4.22/dist/extension.js:39:57022)
        at async uP.provideDocumentSymbols (file:///nix/store/k6h7ajf6sy6g007dq4hlq0kxsgjynnq4-vscode-1.102.3/lib/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:140:127693)

I just checked https://github.com/nix-community/vscode-nix-ide/issues/387 and saw nil have problems.
I can't spent time for seriously investigating why nil failed but replacing it with nixd solved the problem.

Then I can format my codes and enjoy autocompletion.

Signed-off-by: Alireza Arzehgar <alirezaarzehgar82@gmail.com>